[versions]
kotlin = "2.1.10"
moshi = "1.15.2"
retrofit = "2.11.0"
junit = "5.11.4"
truth = "1.4.4"
maven-publish = "0.31.0-rc2"
ktlint = "12.2.0"

[libraries]
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
android-plugin = "com.android.tools.build:gradle:8.9.1"
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.18"
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-java8 = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truth" }
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.9"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.2" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
