[versions]
jdkRelease = "17"
minGradle = "9.0.0"
minAgp = "8.13.0"
minKgp = "2.2.0"

gradle = "9.2.0"

kotlin = "2.2.21"

android-gradle = "8.13.1"

dokka = "2.1.0"

gradle-plugin-publish = "1.3.1"

junit-platform = "6.0.1"

# Pin to 2.12.0 to avoid newer OkHttp versions including newer Kotlin versions. See https://github.com/vanniktech/gradle-maven-publish-plugin/issues/1131
retrofit = "2.12.0"
moshi = "1.15.2"
okhttp = "4.12.0"

slf4j = "1.7.36"

[libraries]
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
android-pluginApi = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle" }
maven-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.1"
junit-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.19"
truth = "com.google.truth:truth:1.4.5"
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.11"
semver = "net.swiftzer.semver:semver:2.1.0"

androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"

[plugins]
buildconfig = "com.github.gmazzo.buildconfig:5.7.1"
android-lint = { id = "com.android.lint", version.ref = "android-gradle" }
