[versions]
kotlin = "1.8.22"
moshi = "1.15.0"
retrofit = "2.9.0"
junit = "5.9.3"
truth = "1.1.3"

[libraries]
okhttp = "com.squareup.okhttp3:okhttp:4.11.0"
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.20"
android-plugin = "com.android.tools.build:gradle:8.0.2"
ktlint-plugin = "org.jlleitschuh.gradle:ktlint-gradle:11.3.2"
maven-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.25.2"
buildconfig-plugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.12"
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-java8 = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truth" }
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.2"

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
