[versions]
jdkRelease = "11"

gradle = "9.1.0"

kotlin = "2.2.20"

android-gradle = "8.13.0"

gradle-plugin-publish = "1.3.1"

junit-platform = "1.14.0"

# Pin to 2.12.0 to avoid newer OkHttp versions including newer Kotlin versions. See https://github.com/vanniktech/gradle-maven-publish-plugin/issues/1131
retrofit = "2.12.0"

[libraries]
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
maven-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.34.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

junit-jupiter = "org.junit.jupiter:junit-jupiter:5.14.0"
junit-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.19"
truth = "com.google.truth:truth:1.4.5"
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.11"

androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"

[plugins]
buildconfig = "com.github.gmazzo.buildconfig:5.6.8"
android-lint = "com.android.lint:8.13.0"
