[versions]
jdkRelease = "11"

gradle = "8.14.3"

kotlin = "2.2.0"

android-gradle = "8.13.0"

gradle-plugin-publish = "1.3.1"

junit-platform = "1.13.4"

[libraries]
okhttp = "com.squareup.okhttp3:okhttp:5.1.0"
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
maven-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.34.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

retrofit = "com.squareup.retrofit2:retrofit:3.0.0"
retrofit-converter-scalars = "com.squareup.retrofit2:converter-scalars:3.0.0"

junit-jupiter = "org.junit.jupiter:junit-jupiter:5.13.4"
junit-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.18"
truth = "com.google.truth:truth:1.4.5"
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.11"

androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"

[plugins]
buildconfig = "com.github.gmazzo.buildconfig:5.6.7"
android-lint = "com.android.lint:8.13.0"
