[versions]
gradle = "8.14.2"

kotlin = "2.1.21"

android-gradle = "8.9.2"

gradle-plugin-publish = "1.3.1"

moshi = "1.15.2"

retrofit = "3.0.0"

truth = "1.4.4"

[libraries]
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
android-plugin = "com.android.tools.build:gradle:8.10.1"
ktlint-plugin = "org.jlleitschuh.gradle:ktlint-gradle:12.3.0"
maven-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.32.0"
bcv = "org.jetbrains.kotlinx:binary-compatibility-validator:0.17.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

junit-jupiter = "org.junit.jupiter:junit-jupiter:5.11.4"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector-junit5:1.18"
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-java8 = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truth" }
truth-testKit = "com.autonomousapps:testkit-truth:1.1"
maven-model = "org.apache.maven:maven-model:3.9.9"

androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"

[plugins]
buildconfig = "com.github.gmazzo.buildconfig:5.6.6"
android-lint = "com.android.lint:8.10.1"
