[versions]
gradle = "9.2.0-rc-1"

kotlin = "2.2.21"

android-gradle = "8.13.0"

gradle-plugin-publish = "2.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
