[versions]
gradle = "9.3.0"

kotlin = "2.3.10-RC"

android-gradle = "9.0.0"

gradle-plugin-publish = "2.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
