[versions]
gradle = "8.14"

kotlin = "2.1.21-RC2"

android-gradle = "8.10.0-rc03"

gradle-plugin-publish = "1.3.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
